---
title: "Aula "
date: 08/11/2023
format: html
editor: visual
---

### Calendário do curso

-   As aulas, agora, vão até o dia 20 de dezembro

-   Teremos até o começo de janeiro de 2024 para entregar o trabalho final

### Instrução para o trabalho

-   Opção 1: Fazer um trabalho original, explorando um dataset de nosso interesse. Neste caso, é necessário comunicar antes ao professor os objetivos para verificar se estão alinhados à proposta do curso

-   Opção 2: Replicar algum estudo. No caso da graduação, serão sugeridos 5 estudos para replicação. Também será preciso comunicar o professor sobre a escolha, mas neste caso para receber orientação

#### O que deve ter no trabalho?

-   Pós-graduação: o trabalho deve ser um paper

-   Graduação:

-   No caso da replicação de um estudo não é necessário refazer a revisão da literatura (de maneira sistemátoca)

#### Expectativas

-   Rodar uma regressão no R

-   Interpretar os resultados corretamente

-   Incorporar ferramentas de análise

-   Análise crítica dos pressupostos do modelo, dos resultados etc.

### Lista 4 - Comentários

Essa lista é obrigatória para a pós-graduação, mas opcional para a graduação

#### Pergunta 1

-   Se estamos interessado no efeito causal de uma variacal binária (0 ou 1)

-   O problema fundamental é que é impossível observar ao mesmo tempo o factual e o contrafactual \[de uma mesma unidade\]

-   Hume

    -   Só observamos associações entre eventos, mas não a causalidade

    -   Exemplo: uma bola de sinuca que bate em outra bola e a faz se movimentar. Neste caso, temos uma associação de eventos, mas não causalidade

    -   A causalidade nunca vai ser observada, porque seria preciso observar o contrafactual (ele não usa esse termo porque não existia na época), que não existe

-   Indo além de Hume: embora não seja possível observar causalidade, posso estabelecer pressupostos e, se tais preesuspostos estiverem corretos, é possível *inferir causalidade*

#### Pergunta 2

-   Objetivo: a trajetória impacta as decisões?

-   Como desenhar a pesquisa para, usando a linguagem de resultados potenciais...

-   Exemplo:

    -   Controle: filiada a partido

    -   Tratamento: ...

-   OBS.: seria possível outros controles e tratamentos (quem foi advogado e quem foi juiz, etc.)

-   Definir o que é trajetória

#### Pergunta 3

-   Viés de seleção: acontece quando temos uma variável colinear que influencia tanto qual unidade vai para o controle e para o tratamento

-   Se existir uma diferenca entre quem estiver no controle estivesse no tratamento teria um comportamento diferente

#### Pergunta 4

-   Neste caso, temos 4 resultados ppotenciais

    -   Se a pessoa foi advogada

    -   Se a pessoa é filiada a partido político

    -   Se a pessoa foi advogada e é filiada

    -   Categoria "outro"

-   Quais categorias formam os grupos de controle e de tratamento?

-   Isso depende da nossa pergunta

-   Exemplos de perguntas: qual o maior efeito causal dos 3 tratamentos (ou 4 se considerarmos a categoria "outro")? Qual o efeito de ter sido advogada?

-   Não podemos rodar uma análise sem especificar

#### Pergunta 5

Qual seria o estimando de seu desenho de pesquisa e qual seria o estimando do desenho de pesquisa da pesquisadora?

-   ATE

-   ATT

No caso da pesquisadora, temos vários estimando possível. Um possível seria comparar o 2 contra o 3

#### Pergunta 6

-   Expectativa de que a nomeação será retribuída por quem foi nomeado

-   Asssim, tanto pessoas que foram advogadas a vida inteira quanto pessoas que foram juízas a vida inteira retribuem o favor que receberam ao serem nomeadas

-   Esses vieses de seleção devem ser controlados \[na regressão?\]

#### Pergunta 7

-   Em estudos observacionais é difícil controlar por todas as variávesi

-   Em estudos experimentais é possível
